# Generated by Django 5.2.6 on 2025-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('creator', 'Creator'), ('clipper', 'Clipper'), ('brand', 'Brand')], default='creator', max_length=50),
        ),
    ]
