# Generated by Django 5.2.6 on 2025-12-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('creator', 'Creator'), ('clipper', 'Clipper'), ('brand', 'Brand')], db_index=True, default='creator', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clips_completed',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
