# Generated by Django 5.2.6 on 2026-02-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='views_generated',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
