# Generated by Django 5.2.6 on 2026-07-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_email_otp_challenge'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotpchallenge',
            new_name='accounts_em_email_04a1ad_idx',
            old_name='accounts_email_otp_challenge_email_expires_inde',
        ),
    ]
