# Generated by Django 5.2.6 on 2026-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_about_company_profile_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='handles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
