# Generated by Django 5.2.6 on 2026-07-23 20:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_contact_number_profile_content_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_cover_upload_path),
        ),
    ]
