"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from datetime import timedelta
from pathlib import Path
from celery.schedules import crontab
from dotenv import load_dotenv


load_dotenv()
print(f"CONNECTING TO: {os.getenv('DATABASE_URL')}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

# For Production ------------------------------------------------------------------------

# DEBUG = False
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True # So cookies are only sent over HTTPS.

# CORS_ALLOW_ALL_ORIGINS = False

# CONN_HEALTH_CHECKS=True # For Neon, So that Django verify active connections before use.


# ---------------------------------------------------------------------------------------

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True').lower() in {'1', 'true', 'yes', 'on'}

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173').split(',')
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # applications for each part of the platform
    'accounts.apps.AccountsConfig',
    'courses',
    'content',
    'earnings',
    'community',
    'leaderboard',
    'notifications',
    'referral',
    'settings',
    'support',
    'creator',
    'drf_spectacular', # for Automated Documentation of API endpoints and payloads @ /api/docs/
    'seed_data', # commands to generate dummy data for testing

    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # django_debug_toolbar Middleware
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Global Logging Middleware
    'core.middleware.GlobalLoggingMiddleware',

]
# Only show the django_debug_toolbar if DEBUG is True and the request is from your IP
INTERNAL_IPS = [
    "127.0.0.1",
]

# Increase the duration the browser caches the preflight response
# 86400 seconds = 24 hours
CORS_PREFLIGHT_MAX_AGE = 86400

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', 'http://127.0.0.1:3000,http://127.0.0.1:5173,http://localhost:5173,https://clinqclip.vercel.app').split(',')
    if origin.strip()
]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)
# Allow common request headers including Cache-Control used by frontend
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'cache-control',
    'Cache-Control',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} [User:{user_id}] {message}',
            'style': '{',
        },
    },
    'filters': {
        'user_id_filter': {
            '()': 'core.middleware.UserIdFilter', # Points to the filter class
        }
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['user_id_filter'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # The empty string '' is the root logger - it catches everything globally
        '': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.server': { # Specific logger for the dev server (manage.py runserver)
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

AUTH_USER_MODEL = 'accounts.CustomUser'

ROOT_URLCONF = 'core.urls'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":(
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day', # Prevents Scrapping 
        'user': '1000/day', # Standard user limit
        'brust': '10/minuite' # For sensitive actions like "Claim"
    },
}

# Celerly/ Redis Conffiguration
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
"""
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Optional: Set the cache timeout (e.g., 15 minutes)
CACHE_TIMEOUT = 60 * 15
"""

def rename_category_enums(result, **kwargs):
    """Post-processing hook to rename category enums in the OpenAPI schema"""

    if 'components' not in result or 'schemas' not in result['components']:
        return result
    
    schemas = result['components']['schemas']
    enum_renames = {}
    
    for schema_name, schema in schemas.items():
        if schema_name.startswith('Category') and 'enum' in schema:
            enum_values = schema.get('enum', [])
            
            # Direct mapping for known generated enum names
            if schema_name == 'Category66aEnum':
                enum_renames[schema_name] = 'SupportTicketCategoryEnum'
            elif schema_name == 'Category637Enum':
                enum_renames[schema_name] = 'DiscussionCategoryEnum'
            # Fallback: Identify by enum values
            # SupportTicket category enum (has 'technical', 'billing', 'account', 'content', 'feature', 'other')
            elif 'technical' in enum_values and 'billing' in enum_values and 'other' in enum_values and 'feature' in enum_values:
                enum_renames[schema_name] = 'SupportTicketCategoryEnum'
            # Discussion category enum (has 'general', 'tips', 'showcase', 'help', 'announcements')
            elif 'tips' in enum_values and 'showcase' in enum_values and 'announcements' in enum_values and 'help' in enum_values:
                enum_renames[schema_name] = 'DiscussionCategoryEnum'
            # FAQ category enum (has 'general', 'getting_started', 'earnings')
            elif 'general' in enum_values and 'getting_started' in enum_values and 'earnings' in enum_values:
                enum_renames[schema_name] = 'FAQCategoryEnum'
            # Content category enum (has 'gaming', 'lifestyle', 'education', 'entertainment', 'technology')
            elif 'gaming' in enum_values and 'lifestyle' in enum_values and 'entertainment' in enum_values:
                enum_renames[schema_name] = 'ContentCategoryEnum'
            # Course category enum (has 'editing', 'content-creation', 'business', 'marketing')
            elif 'editing' in enum_values and 'content-creation' in enum_values:
                enum_renames[schema_name] = 'CourseCategoryEnum'
    
    # Rename schemas and update all references
    for old_name, new_name in enum_renames.items():
        if old_name in schemas:
            schemas[new_name] = schemas.pop(old_name)
            # Update references recursively throughout the entire schema
            _update_refs_recursive(result, old_name, new_name)
    
    return result


def _update_refs_recursive(obj, old_name, new_name):
    """Recursively update $ref references in the schema"""
    if isinstance(obj, dict):
        if '$ref' in obj and (obj['$ref'].endswith(old_name) or f'/{old_name}' in obj['$ref']):
            obj['$ref'] = obj['$ref'].replace(old_name, new_name)
        for value in obj.values():
            _update_refs_recursive(value, old_name, new_name)
    elif isinstance(obj, list):
        for item in obj:
            _update_refs_recursive(item, old_name, new_name)


# for Automated API docs
SPECTACULAR_SETTINGS = {
    'TITLE': 'ClinqClippers SuperApp API',
    'DESCRIPTION': 'Creator & UGC ecosystem with integrated clipping, music, and brand tools.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # To enable JWT testing in Swagger:
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    # Include all ViewSets and actions in schema
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and profile management'},
        {'name': 'Courses', 'description': 'Course management and enrollment'},
        {'name': 'Content', 'description': 'Content creation and clipping'},
        {'name': 'Community', 'description': 'Discussions, replies, and events'},
        {'name': 'Earnings', 'description': 'Earnings overview and payouts'},
        {'name': 'Leaderboard', 'description': 'User rankings and leaderboards'},
        {'name': 'Referral', 'description': 'Referral system and invites'},
        {'name': 'Settings', 'description': 'User settings and preferences'},
        {'name': 'Support', 'description': 'Support tickets and FAQs'},
    ],
    # Auto-generate schema for all ViewSets
    'SCHEMA_PATH_PREFIX': '/api/',
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    # Post-processing hook to rename category enums after schema generation
    # Note: We can't mix string paths with function objects, so we'll use a wrapper
    'POSTPROCESSING_HOOKS': [
        'core.settings.rename_category_enums',
    ],
}


# to store media uploaded
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'  

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
DB_CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', '0' if DATABASE_URL and 'pooler.supabase.com' in DATABASE_URL else '600'))
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=DB_CONN_MAX_AGE,
            ssl_require=False,
            test_options={'NAME': os.getenv('TEST_DATABASE_NAME', 'clinq_test_db')},
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'clinq',
            'USER': 'postgres',
            'PASSWORD': 'postgres',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Expose Supabase and frontend public values from environment so views can
# return them to the frontend when needed (safe: anon key only)
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY') or os.getenv('SUPABASE_SERVICE_ROLE')
# If a dedicated anon key is provided, prefer it; fall back to SUPABASE_KEY in dev only
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY') or os.getenv('SUPABASE_KEY')

# -------------------- Email (SMTP) for OTP sending --------------------
# IMPORTANT: In production, do NOT hardcode credentials. Use env vars.
# These defaults are provided so OTP mail works out-of-the-box for local/dev.
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'tech.clinqclip@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'qrmh ovry qeom zsgr')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in {'1', 'true', 'yes', 'on'}
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'tech.clinqclip@gmail.com')


# Public frontend configuration values (optional)
VITE_API_BASE_URL = os.getenv('VITE_API_BASE_URL') or os.getenv('API_BASE_URL') or 'http://localhost:8000/'
VITE_OAUTH_REDIRECT_URL = os.getenv('VITE_OAUTH_REDIRECT_URL')
FRONTEND_URL = os.getenv('FRONTEND_URL') or os.getenv('VITE_OAUTH_REDIRECT_URL', 'http://localhost:5173').split('/oauth')[0].split('/auth/callback')[0] or 'http://localhost:5173'

import sys 
if 'test' in sys.argv:
    if DATABASE_URL:
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=DB_CONN_MAX_AGE,
                ssl_require=False,
                test_options={'NAME': os.getenv('TEST_DATABASE_NAME', 'clinq_test_db')},
            )
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'test_db.sqlite3',
            }
        }
    # Use dummy cache during tests so throttling doesn't try to hit Redis
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    # Disable throttling entirely during tests
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []