# Generated by Django 5.2.6 on 2026-02-12 19:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Broadcast title', max_length=255)),
                ('message', models.TextField(help_text='Broadcast message content')),
                ('category', models.CharField(choices=[('system', 'System'), ('content', 'Content'), ('course', 'Course'), ('admin', 'Admin'), ('community', 'Community'), ('support', 'Support'), ('leaderboard', 'Leaderboard'), ('referral', 'Referral'), ('earnings', 'Earnings')], default='admin', help_text='Notification category', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('target_user_type', models.CharField(blank=True, choices=[('', 'All Users'), ('creator', 'Creator'), ('clipper', 'Clipper'), ('brand', 'Brand')], db_index=True, default='', help_text='Specific user type to target (empty = all users)', max_length=50)),
                ('target_segment', models.CharField(blank=True, default='', help_text="Optional segment filter (e.g., 'premium', 'active')", max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether broadcast is active')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='When to send the broadcast', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the broadcast expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_recipients', models.IntegerField(default=0, help_text='Number of users who received this broadcast')),
                ('read_count', models.IntegerField(default=0, help_text='Number of users who read this broadcast')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_notifications_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Notification',
                'verbose_name_plural': 'Broadcast Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='notifications.broadcastnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text="Type of event (e.g., 'content.clipped', 'earnings.paid')", max_length=100)),
                ('entity_type', models.CharField(db_index=True, help_text="Type of entity (e.g., 'content', 'user', 'leaderboard')", max_length=50)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, help_text='ID of the related entity', null=True)),
                ('title', models.CharField(blank=True, default='', help_text='Notification title template', max_length=255)),
                ('message', models.TextField(default='Hello', help_text='Notification message content')),
                ('payload', models.JSONField(default=dict, help_text='Additional event metadata (JSON)')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate events', max_length=255, unique=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', help_text='Event priority for sorting', max_length=20)),
                ('category', models.CharField(choices=[('system', 'System'), ('content', 'Content'), ('course', 'Course'), ('admin', 'Admin'), ('community', 'Community'), ('support', 'Support'), ('leaderboard', 'Leaderboard'), ('referral', 'Referral'), ('earnings', 'Earnings')], db_index=True, default='system', max_length=50)),
                ('rate_limit_key', models.CharField(blank=True, db_index=True, default='', help_text="Key for rate limiting (e.g., 'user:123:content')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Event',
                'verbose_name_plural': 'Notification Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('system', 'System'), ('content', 'Content'), ('course', 'Course'), ('admin', 'Admin'), ('community', 'Community'), ('support', 'Support'), ('leaderboard', 'Leaderboard'), ('referral', 'Referral'), ('earnings', 'Earnings')], db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push')], db_index=True, max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether user has read this notification')),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Soft delete - archived by user')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When user marked this as read', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='notifications.notificationevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['is_active', '-created_at'], name='notificatio_is_acti_037568_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['target_user_type', '-created_at'], name='notificatio_target__e3f1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastnotification',
            index=models.Index(fields=['scheduled_at', 'is_active'], name='notificatio_schedul_864756_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastreadreceipt',
            index=models.Index(fields=['broadcast', 'user'], name='notificatio_broadca_586359_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastreadreceipt',
            unique_together={('user', 'broadcast')},
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_d4510d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['category', '-created_at'], name='notificatio_categor_ffed86_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['actor', '-created_at'], name='notificatio_actor_i_1ce4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'category'], name='notificatio_user_id_e0a7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'channel'], name='notificatio_user_id_016cb8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'category', 'channel')},
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_776dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_bf9fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_archived', '-created_at'], name='notificatio_user_id_5347f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'event')},
        ),
    ]
