# Generated by Django 5.2.6 on 2025-12-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0003_alter_transaction_options_transaction_bot_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Successful'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('earning', 'Viral Earning'), ('withdrawal', 'Withdrawal'), ('commission', 'Platform Fee'), ('listing_fee', 'Premium Listing'), ('bid_fee', 'Premium Bid Fee')], db_index=True, max_length=20),
        ),
    ]
