# Generated by Django 5.2.6 on 2026-08-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0004_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_details',
            field=models.CharField(blank=True, help_text='UPI ID or bank transfer details', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], db_index=True, max_length=20),
        ),
    ]
