import {
    Shirt,
    Trophy,
    Mic2,
    Smartphone,
    Palette,
    Film,
  } from "lucide-react";
  
  import {
    FaInstagram,
    FaYoutube,
    FaFacebookF,
    FaXTwitter,
  } from "react-icons/fa6";
  
  export const featuredCampaigns = [
    {
      id: 1,
      brand: "Nike",
      brandLogo: "https://cdn.simpleicons.org/nike/ffffff",
      title: "Summer Creator Challenge",
      category: "Fashion",
      icon: Shirt,
      accent: "violet",
      status: "Active",
      thumbnail: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&q=80",
      views: 1250000,
      submissions: 324,
      budget: 50000,
      paidOut: 18200,
      platforms: [FaInstagram, FaYoutube],
      description:
        "Create a short-form video showcasing Nike's Summer '26 collection in your own style. We're looking for authentic, energetic content — think workout clips, street style, or lifestyle vlogs that naturally feature the gear.",
      requirements: [
        "Video length: 15–60 seconds",
        "Must tag @nike and use #NikeSummerChallenge",
        "Original content only, no reposts",
        "Minimum 5K followers on submission platform",
      ],
      deadline: "Aug 30, 2026",
      payoutPerSubmission: "₹500 – ₹5,000 based on views",
    },
    {
      id: 7,
      brand: "Puma",
      brandLogo: "https://cdn.simpleicons.org/puma/ffffff",
      title: "Street Style Sprint",
      category: "Fashion",
      icon: Shirt,
      accent: "violet",
      status: "Active",
      thumbnail: "https://images.unsplash.com/photo-1483721310020-03333e577078?w=1200&q=80",
      views: 540000,
      submissions: 156,
      budget: 30000,
      paidOut: 8400,
      platforms: [FaInstagram, FaYoutube],
      description: "Show off Puma's new street collection in your everyday content — commute clips, gym fits, city walks.",
      requirements: [
        "Video length: 15–45 seconds",
        "Tag @puma and use #StreetStyleSprint",
        "Original footage only",
      ],
      deadline: "Sep 5, 2026",
      payoutPerSubmission: "₹400 – ₹4,000 based on views",
      resources: [
        { label: "Brand Guidelines (PDF)", url: "https://example.com/puma-guidelines.pdf" },
        { label: "Logo & Asset Pack", url: "https://example.com/puma-assets.zip" },
        { label: "Approved Hashtag List", url: "https://example.com/puma-hashtags" },
      ],
    },
    {
      id: 8,
      brand: "Sony Music",
      brandLogo: "https://cdn.simpleicons.org/sonymusic/ffffff",
      title: "New Release Reaction Clips",
      category: "Music",
      icon: Mic2,
      accent: "amber",
      status: "Active",
      thumbnail: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80",
      views: 410000,
      submissions: 98,
      budget: 22000,
      paidOut: 5100,
      platforms: [FaInstagram, FaYoutube, FaXTwitter],
      description: "React to Sony Music's latest single drop and share your honest take, dance, or cover on your platform of choice.",
      requirements: [
        "Video length: 20–90 seconds",
        "Must include a 5-second clip of the track",
        "Tag the artist's official handle",
      ],
      deadline: "Aug 20, 2026",
      payoutPerSubmission: "₹300 – ₹3,500 based on views",
      resources: [
        { label: "Track Preview (Audio)", url: "https://example.com/sony-preview.mp3" },
        { label: "Press Kit", url: "https://example.com/sony-presskit.pdf" },
      ],
    },
  ]