import uuid
import decimal

from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

# Import notifications helpers for integration
try:
    from notifications.helpers import (
        notify_course_enrollment,
        notify_course_completion,
        notify_course_new
    )
    NOTIFICATIONS_AVAILABLE = True
except ImportError:
    NOTIFICATIONS_AVAILABLE = False
    notify_course_enrollment = None
    notify_course_completion = None
    notify_course_new = None

class Course(models.Model):
    CATEGORY_CHOICES = [
        ('editing', 'Video Editing'),
        ('content-creation', 'Content Creation'),
        ('business', 'Business'),
        ('marketing', 'Marketing'),
        ('other', 'Other'),
    ]
    LEVEL_CHOICES = [
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Advanced', 'Advanced'),
        ('All Levels', 'All Levels'),
    ]

    title = models.CharField(max_length=255)
    description = models.TextField()
    instructor = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='instructed_courses',
        db_index=True
    )
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='editing')

    # Pricing
    price = models.DecimalField(max_digits=8, decimal_places=2)
    original_price = models.DecimalField(max_digits=8, decimal_places=2)

    # Stats
    rating = models.DecimalField(max_digits=3, decimal_places=1, default=decimal.Decimal("0.0"))
    reviews_count = models.IntegerField(default=0)
    students_count = models.PositiveIntegerField(default=0) # Stored as int (e.g., 12500), formatted in serializer

    # Meta
    duration = models.CharField(max_length=50) # e.g., "8.5 hours"
    lessons_count = models.PositiveIntegerField(default=0)
    level = models.CharField(max_length=50, choices=LEVEL_CHOICES)

    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self) -> str:
        return self.title
    
class LearningPath(models.Model):

    title = models.CharField(max_length=255)
    description = models.TextField()
    courses_count = models.IntegerField()
    duration_str = models.CharField(max_length=50) # e.g., "24 hours"
    has_certificate = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.title
    

class CourseEnroll(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, 
        related_name='enrollment'
        )
    course = models.ForeignKey(
        'Course', 
        on_delete=models.CASCADE,
        related_name='enrollments'
        )
    enrolled_at = models.DateTimeField(auto_now_add=True)
    progress = models.IntegerField(default=0) # Track 0-100% completion
    is_completed = models.BooleanField(default=False)

    class Meta:
        # Prevents a user from enrolling in the same course twice
        unique_together = ('user', 'course') 

    def __str__(self):
        return f"{self.user.email} enrolled in {self.course.title}"
    
class Lesson(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending Upload'), # Link generated, but file not yet on Supabase
        ('processing', 'Processing Video'), # File uploaded, Celery is extracting metadata
        ('ready', 'Ready'), # Video is live
        ('failed', 'Failed')
    ]

    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    
    # Media: StorSupabase/S3)
    video_path = models.CharField(max_length=500, blank=True, help_text="Intenal Storage (Supabase) path")
    video_url = models.URLField(blank=True, null=True, help_text="Publically accessible URL")
    thumbnail_url = models.CharField(max_length=500, blank=True, help_text="Thumbnail generated by ffmpeg")
    
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='pending'
    )
    duration = models.CharField(max_length=20, default="0:00", help_text="e.g., 10:25")
    # Ordering Logic
    order = models.PositiveIntegerField(default=0, help_text="The sequence number of the lesson")
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order'] # Ensures Lesson 1 always comes before Lesson 2

    def __str__(self):
        return f"{self.course.title} - {self.title}"


# Signal handlers for notifications
@receiver(post_save, sender=CourseEnroll)
def course_enrollment_notification_handler(sender, instance, created, **kwargs):
    """
    Send notifications when users enroll or complete courses
    """
    if not NOTIFICATIONS_AVAILABLE:
        return
    
    user_id = str(instance.user.id)
    course_id = str(instance.course.id)
    course_name = instance.course.title
    instructor_name = instance.course.instructor
    
    # Notify when user enrolls in a course
    if created and notify_course_enrollment:
        try:
            notify_course_enrollment(
                user_id=uuid.UUID(user_id),
                course_id=uuid.UUID(course_id),
                course_title=course_name,
                instructor_name=instructor_name
                )
        except Exception as e:
            import logging
            logging.getLogger(__name__).error(
                f"Failed to send enrollment notification: {e}"
            )
    
    # Notify when user completes a course
    if instance.is_completed and notify_course_completion:
        # Check if this is the moment completion happened
        if kwargs.get('update_fields') is None or 'is_completed' in (kwargs.get('update_fields') or []):
            try:
                notify_course_completion(
                    user_id=uuid.UUID(user_id),
                    course_id=uuid.UUID(course_id),
                    course_title=course_name,
                    certificate_id=None
                )
            except Exception as e:
                import logging
                logging.getLogger(__name__).error(
                    msg=f"Failed to send completion notification: {e}"
                )