# Generated by Django 5.2.6 on 2025-12-21 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(unique=True)),
                ('platform', models.CharField(max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_moderated', models.BooleanField(default=False)),
                ('meets_instructions', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payout_triggered', models.BooleanField(default=False)),
                ('clipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.content')),
            ],
        ),
    ]
