# Generated by Django 5.2.6 on 2025-12-21 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_clipsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
