# Generated by Django 5.2.6 on 2026-01-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_content_category_alter_content_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clipsubmission',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clipsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_submissions', to='content.content'),
        ),
        migrations.AlterField(
            model_name='clipsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('sports', 'Sports'), ('music', 'Music'), ('art', 'Art'), ('cooking', 'Cooking'), ('fitness', 'Fitness')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('review', 'In Review'), ('completed', 'Completed')], db_index=True, default='available', max_length=20),
        ),
    ]
