# Generated by Django 5.2.6 on 2026-01-18 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_bid_status_alter_clipsubmission_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_gigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
