# Generated by Django 5.2.6 on 2026-02-11 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_paid_listing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-is_paid_listing', '-created_at'], name='content_con_is_paid_7a0c36_idx'),
        ),
    ]
