# Generated by Django 5.2.6 on 2026-07-18 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_content_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('lifestyle', 'Lifestyle'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('sports', 'Sports'), ('music', 'Music'), ('art', 'Art'), ('cooking', 'Cooking'), ('fitness', 'Fitness'), ('podcast', 'Podcast'), ('finance', 'Finance')], db_index=True, max_length=50)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('clipper_requirements', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reward_per_1k', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('completed', 'Completed')], db_index=True, default='active', max_length=20)),
                ('views', models.BigIntegerField(default=0)),
                ('submissions', models.PositiveIntegerField(default=0)),
                ('paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='content.campaign')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['creator', '-created_at'], name='content_cam_creator_ff6d22_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='content_cam_status_740e74_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignresource',
            index=models.Index(fields=['campaign', 'order'], name='content_cam_campaig_4c6577_idx'),
        ),
    ]
