# Generated by Django 5.2.6 on 2026-07-24 15:26

import django.db.models.deletion
from django.db import migrations, models


def create_or_update_campaignsubmission_table(apps, schema_editor):
    connection = schema_editor.connection
    cursor = connection.cursor()
    table_name = 'content_campaignsubmission'
    existing_tables = connection.introspection.table_names()

    if table_name not in existing_tables:
        if connection.vendor == 'sqlite':
            cursor.execute(
                """
                CREATE TABLE content_campaignsubmission (
                    id integer PRIMARY KEY AUTOINCREMENT,
                    participant_id integer,
                    platform varchar(20) NOT NULL,
                    platform_username varchar(100) NOT NULL DEFAULT '',
                    post_url text NOT NULL DEFAULT '',
                    earning numeric(10,2) NOT NULL DEFAULT 0,
                    likes integer NOT NULL DEFAULT 0,
                    views integer NOT NULL DEFAULT 0,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                """
            )
        else:
            cursor.execute(
                """
                CREATE TABLE content_campaignsubmission (
                    id bigserial PRIMARY KEY,
                    participant_id bigint,
                    platform varchar(20) NOT NULL,
                    platform_username varchar(100) NOT NULL DEFAULT '',
                    post_url text NOT NULL DEFAULT '',
                    earning numeric(10,2) NOT NULL DEFAULT 0,
                    likes integer NOT NULL DEFAULT 0,
                    views integer NOT NULL DEFAULT 0,
                    status varchar(20) NOT NULL DEFAULT 'pending',
                    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                """
            )

    try:
        columns = {row.name for row in connection.introspection.get_table_description(cursor, table_name)}
    except Exception:
        columns = set()

    if 'participant_id' not in columns:
        cursor.execute("ALTER TABLE content_campaignsubmission ADD COLUMN participant_id bigint")
    if 'platform_username' not in columns:
        cursor.execute("ALTER TABLE content_campaignsubmission ADD COLUMN platform_username varchar(100) NOT NULL DEFAULT ''")
    if 'earning' not in columns:
        cursor.execute("ALTER TABLE content_campaignsubmission ADD COLUMN earning numeric(10,2) NOT NULL DEFAULT 0")
    if 'likes' not in columns:
        cursor.execute("ALTER TABLE content_campaignsubmission ADD COLUMN likes integer NOT NULL DEFAULT 0")
    if 'status' not in columns:
        cursor.execute("ALTER TABLE content_campaignsubmission ADD COLUMN status varchar(20) NOT NULL DEFAULT 'pending'")
    if 'created_at' not in columns:
        cursor.execute("ALTER TABLE content_campaignsubmission ADD COLUMN created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_campaignparticipant'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_or_update_campaignsubmission_table, reverse_code=noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CampaignSubmission',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20)),
                        ('platform_username', models.CharField(blank=True, max_length=100)),
                        ('content_url', models.URLField(db_column='post_url', blank=True)),
                        ('earning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                        ('likes', models.IntegerField(default=0)),
                        ('views', models.IntegerField(default=0)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.campaignparticipant')),
                    ],
                    options={
                        'db_table': 'content_campaignsubmission',
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['participant', 'status'], name='content_cam_partici_5d2b0a_idx')],
                    },
                ),
            ],
        ),
    ]
