# Generated by Django 5.2.6 on 2026-07-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_cleanup_campaignsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
