# Generated by Django 5.2.6 on 2026-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_campaign_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='active', max_length=20),
        ),
    ]
