# Generated by Django 5.2.6 on 2026-07-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
