# Generated by Django 5.2.6 on 2026-07-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_campaignsubmission_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
