# Generated by Django 5.2.6 on 2026-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_campaignsubmission_is_deleted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaign',
            new_name='content_cam_type_04fe95_idx',
            old_name='content_camp_type_st_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('available', 'Available'), ('claimed', 'Claimed'), ('review', 'In Review'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignsubmission',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clipsubmission',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X')], max_length=20),
        ),
    ]
