# Generated by Django 5.2.6 on 2026-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_rename_content_camp_type_st_idx_content_cam_type_04fe95_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsubmission',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='review_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
    ]
