# Generated by Django 5.2.6 on 2026-09-01 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_campaignsubmission_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsubmission',
            name='payout_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='payout_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('held', 'Held')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='payout_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignsubmission',
            name='payout_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payout_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
