# Generated by Django 5.2.6 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_campaignsubmission_payout_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('deadline', 'Deadline'), ('budget', 'Budget exhausted'), ('manual', 'Manual')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='remaining_funds_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='remaining_funds_settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='remaining_funds_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
