# Generated by Django 5.2.6

import uuid
from django.db import migrations, models


def _populate_access_keys(apps, schema_editor):
    Campaign = apps.get_model('content', 'Campaign')
    for campaign in Campaign.objects.filter(public_access_key__isnull=True).iterator():
        Campaign.objects.filter(pk=campaign.pk).update(public_access_key=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_campaign_closure_settlement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='public_access_key',
            field=models.UUIDField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.RunPython(
            code=_populate_access_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='public_access_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
