# Generated by Django 5.2.6 on 2026-09-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_unique_active_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='final_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='proxy_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='review_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
