# Generated by Django 5.2.6 on 2026-01-08 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('creators', 'Creators'), ('clippers', 'Clippers'), ('brands', 'Brands'), ('overall', 'Overall')], max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('rank', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clips_completed', models.IntegerField(default=0)),
                ('content_created', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField(help_text='Start of the ranking period')),
                ('period_end', models.DateTimeField(help_text='End of the ranking period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'period', 'rank'],
                'indexes': [models.Index(fields=['category', 'period', '-score', 'rank'], name='leaderboard_categor_eac329_idx'), models.Index(fields=['user', 'category', 'period'], name='leaderboard_user_id_8e9f13_idx')],
                'unique_together': {('user', 'category', 'period', 'period_start')},
            },
        ),
    ]
