# Generated by Django 5.2.6 on 2026-01-08 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('earnings_notifications', models.BooleanField(default=True)),
                ('content_notifications', models.BooleanField(default=True)),
                ('social_notifications', models.BooleanField(default=True)),
                ('marketing_notifications', models.BooleanField(default=False)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='public', max_length=20)),
                ('show_earnings', models.BooleanField(default=True, help_text='Show earnings on profile')),
                ('show_email', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='dark', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_content_category', models.CharField(blank=True, max_length=50)),
                ('auto_claim_enabled', models.BooleanField(default=False, help_text='Auto-claim content matching skills')),
                ('preferred_payout_method', models.CharField(choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], default='upi', max_length=20)),
                ('payout_threshold', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
