# Generated by Django 5.2.6 on 2025-12-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('editing', 'Video Editing'), ('content-creation', 'Content Creation'), ('business', 'Business'), ('marketing', 'Marketing')], default='editing', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=0)),
                ('students_count', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=50)),
                ('lessons_count', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All Levels', 'All Levels')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPAth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('courses_count', models.IntegerField()),
                ('duration_str', models.CharField(max_length=50)),
                ('has_certificate', models.BooleanField(default=True)),
            ],
        ),
    ]
