# Generated by Django 5.2.6 on 2026-02-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('processing', 'Processing Video'), ('ready', 'Ready'), ('failed', 'Failed')], default='penidng', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.CharField(blank=True, help_text='Thumbnail generated by ffmpeg', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_path',
            field=models.CharField(blank=True, help_text='Intenal Storage (Supabase) path', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='0:00', help_text='e.g., 10:25', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Publically accessible URL', null=True),
        ),
    ]
