# Generated by Django 5.2.6 on 2026-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_status_lesson_thumbnail_url_lesson_video_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('editing', 'Video Editing'), ('content-creation', 'Content Creation'), ('business', 'Business'), ('marketing', 'Marketing'), ('other', 'Other')], default='editing', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('processing', 'Processing Video'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
