# Generated by Django 4.2.30 on 2026-08-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorsubmission',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
